nameOverride: "postgres"
fullnameOverride: "postgres"

image:
  repository: postgres
  pullPolicy: Always
  tag: "13"

service:
  type: ClusterIP
  port: 5432

serviceAccount:
  create: false

auth:
  username: "meo_admin"
  password: "MeoStationery2025!" # <-- Change for production and manage securely
  database: "meo_stationery"

persistence:
  size: 1Gi
  storageClassName: gp2-ap-southeast-2a
  provisionStorageClass: true
  allowedTopologies:
    - key: topology.ebs.csi.aws.com/zone
      values:
        - ap-southeast-2a

nodeSelector:
  role: db

livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
