apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenkins.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-port
      protocol: TCP
      name: http
    - port: 50000
      targetPort: jnlp-port
      protocol: TCP
      name: jnlp
  selector:
    {{- include "jenkins.selectorLabels" . | nindent 4 }}


